=== Wes-Ley-Cor-Ean-O39/FMU/IMAG_RECORTE_ASSINATURA/GCC/SERVICOS/APP/GCC_IMAG_RECORTE/imag.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.wvs.com.br/imag" elementFormDefault="unqualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.wvs.com.br/imag">

    <complexType name="produto">
    	<sequence>
    		<element name="configuracao" type="tns:configuracao" minOccurs="1" maxOccurs="1"></element>
    		<choice minOccurs="1" maxOccurs="1">
    			<element name="posicaoCsvGccd" type="tns:posicaoCsvGccd" minOccurs="1" maxOccurs="1"></element>
    			<element name="posicaoCsvAthic" type="tns:posicaoCsvAthic" maxOccurs="1" minOccurs="1"></element>
    		</choice>
    		<choice minOccurs="0" maxOccurs="1">
	    		<element name="rastreabilidade" type="tns:rastreabilidade" minOccurs="0" maxOccurs="1"></element>
    		</choice>
    	</sequence>
    </complexType>

    <complexType name="configuracao">
    	<sequence>
    	
            <element name="capacidadeMaximaEBCDIC" maxOccurs="1" minOccurs="1">
    			<simpleType>
    				<restriction base="int">
    					<minInclusive value="1"></minInclusive>
    				</restriction>
    			</simpleType>
    		</element>
    		
            <element name="prefixoCartaoAssinatura" minOccurs="1" maxOccurs="1">
    			<simpleType>
    				<restriction base="string">
    					<minLength value="1"></minLength>
    				</restriction>
    			</simpleType>
    		</element>
    		
            <element name="caminhoOrigem" minOccurs="1" maxOccurs="1">
    			<simpleType>
    				<restriction base="string">
    					<minLength value="1"></minLength>
    				</restriction>
    			</simpleType>
    		</element>
    		
    		<element name="caminhoDestino" minOccurs="1" maxOccurs="1">
    			<simpleType>
    				<restriction base="string">
    					<minLength value="1"></minLength>
    				</restriction>
    			</simpleType>
    		</element>
    		
    		<element name="criarArquivoTopDestino" type="boolean" maxOccurs="1" minOccurs="1"></element>
    		
    		<element name="caminhoRejeitado" minOccurs="1" maxOccurs="1">
    			<simpleType>
    				<restriction base="string">
    					<minLength value="1"></minLength>
    				</restriction>
    			</simpleType>
    		</element>
    		
    		<element name="caminhoSaidaEbcdic" maxOccurs="1" minOccurs="1">
    			<simpleType>
    				<restriction base="string">
    					<minLength value="1"></minLength>
    				</restriction>
    			</simpleType>
    		</element>
    		
    		<element name="sleep" minOccurs="1" maxOccurs="1">
    			<simpleType>
    				<restriction base="int">
    					<minInclusive value="1"></minInclusive>
    				</restriction>
    			</simpleType>
    		</element>
    		
    		<element name="tempRastreabilidade" maxOccurs="1" minOccurs="0">
    			<simpleType>
    				<restriction base="string">
    					<minLength value="1"></minLength>
    				</restriction>
    			</simpleType>
    		</element>
    		
    		<element name="caminhoRejeitadosRastreabilidade" maxOccurs="1" minOccurs="0">
    			<simpleType>
    				<restriction base="string">
    					<minLength value="1"></minLength>
    				</restriction>
    			</simpleType>
    		</element>
    		
    		<element name="descompactarTemp" maxOccurs="1" minOccurs="0">
	    		<simpleType>
	    				<restriction base="string">
	    					<minLength value="1"></minLength>
	    				</restriction>
	    		</simpleType>
    		</element>
    		
    	</sequence>
    </complexType>

    <complexType name="posicaoCsv">
    	
    	<sequence>
    		
    		<element name="nomeDoArquivo" minOccurs="1" maxOccurs="1">
    			<simpleType>
    				<restriction base="int">
    					<minInclusive value="0"></minInclusive>
    				</restriction>
    			</simpleType>
    		</element>
    		
    		<element name="agencia" minOccurs="1" maxOccurs="1">
    			<simpleType>
    				<restriction base="int">
    					<minInclusive value="0"></minInclusive>
    				</restriction>
    			</simpleType>
    		</element>
    		
    		<element name="conta" minOccurs="1" maxOccurs="1">
    			<simpleType>
    				<restriction base="int">
    					<minInclusive value="0"></minInclusive>
    				</restriction>
    			</simpleType>
    		</element>
    		
    		<element name="tipoDaConta" minOccurs="1" maxOccurs="1">
    			<simpleType>
    				<restriction base="int">
    					<minInclusive value="0"></minInclusive>
    				</restriction>
    			</simpleType>
    		</element>
    		
    		<element name="cpf" minOccurs="1" maxOccurs="1">
    			<simpleType>
    				<restriction base="int">
    					<minInclusive value="0"></minInclusive>
    				</restriction>
    			</simpleType>
    		</element>
    		
    	</sequence>
    	
    </complexType>

    <element name="produto" type="tns:produto"></element>

    <complexType name="posicaoCsvAthic">
    
    	<complexContent>
    		<extension base="tns:posicaoCsv">
    			<sequence>
    				<element name="nomeDocumento" type="int"
    					maxOccurs="1" minOccurs="1" nillable="false">
    				</element>
    			</sequence>
    			<attribute name="origem" type="int" use="required" fixed="3"></attribute>
    		</extension>
    	</complexContent>
    	
    </complexType>
    

    <complexType name="posicaoCsvGccd">
    
    	<complexContent>
    		<extension base="tns:posicaoCsv">
    			<attribute name="origem" type="int" use="required" fixed="2"></attribute>
    		</extension>
    	</complexContent>
    	
    </complexType>
  
    <complexType name="rastreabilidade">
    
    	<sequence>
    	
    		<element name="niur" minOccurs="0" maxOccurs="1" />
    		<element name="niurPrincipal" minOccurs="0" maxOccurs="1" />
    		<element name="hashImagem" minOccurs="0" maxOccurs="1" />
    		<element name="codigoFluxoArmazenamento" minOccurs="0" maxOccurs="1" />
    		<element name="numeroProcesso" minOccurs="0" maxOccurs="1" />
    		<element name="bancoCaptura" minOccurs="0" maxOccurs="1" />
    		<element name="bancoProcessamento" minOccurs="0" maxOccurs="1" />
    		<element name="banco" minOccurs="0" maxOccurs="1" />
    		<element name="agenciaCaptura" minOccurs="0" maxOccurs="1" />
    		<element name="agenciaProcessamento" minOccurs="0" maxOccurs="1" />
    		<element name="agencia" minOccurs="0" maxOccurs="1" />
    		<element name="conta" minOccurs="0" maxOccurs="1" />
    		<element name="cpfCnpj" minOccurs="0" maxOccurs="1" />
    		<element name="filialCnpj" minOccurs="0" maxOccurs="1" />
    		<element name="controleCpfCnpj" minOccurs="0" maxOccurs="1" />
    		<element name="icorPessoa" minOccurs="0" maxOccurs="1" />
    		<element name="cmc7" minOccurs="0" maxOccurs="1" />
    		<element name="situacaoIntegridade" minOccurs="0" maxOccurs="1" />	
    		<element name="situacaoProcessamento" minOccurs="0" maxOccurs="1" />		
    		<element name="situacaoDocumento" minOccurs="0" maxOccurs="1" />		
    		<element name="mimeType" minOccurs="0" maxOccurs="1" />		
    		<element name="nomeArquivo" minOccurs="0" maxOccurs="1" />			
    		<element name="codigoDocumento" minOccurs="0" maxOccurs="1" />	
    		<element name="codigoServicoRecepcao" minOccurs="0" maxOccurs="1" />
    		
    	</sequence>
    	
    	<attribute name="gerar" type="boolean" ></attribute>
    	<attribute name="moverRastreabilidade" type="boolean" ></attribute>
    	<attribute name="trigger" type="boolean" ></attribute>
    	<attribute name="validarIntegridade" type="boolean" ></attribute>
    	
    </complexType>
    
</schema>

=== Wes-Ley-Cor-Ean-O39/FMU/IMAG_RECORTE_ASSINATURA/ICC_GCC/ACTAS_DESMAT/IMAG/CONFIG/IMAG/PRODUTO/CTAS_DESMAT.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:produto xmlns:tns="http://www.wvs.com.br/imag" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.wvs.com.br/imag imag.xsd ">
	
	<configuracao>
		<capacidadeMaximaEBCDIC>1</capacidadeMaximaEBCDIC>
		<prefixoCartaoAssinatura>c_</prefixoCartaoAssinatura>
		<caminhoOrigem>C:\ICC_GCC\ACTAS_DESMAT\IMAG\ORIGEM</caminhoOrigem>
		<caminhoDestino>C:\ICC_GCC\ACTAS_DESMAT\IMAG\DESTINO</caminhoDestino>
		<criarArquivoTopDestino>false</criarArquivoTopDestino>
		<caminhoRejeitado>C:\ICC_GCC\ACTAS_DESMAT\IMAG\REJEITADO</caminhoRejeitado>
		<caminhoSaidaEbcdic>C:\ICC_GCC\ACTAS_DESMAT\IMAG\\EBCDIC</caminhoSaidaEbcdic>
		<sleep>1</sleep>
		<tempRastreabilidade>C:\ICC_GCC\ACTAS_DESMAT\IMAG\TEMPORARIO_RAST</tempRastreabilidade>
		<caminhoRejeitadosRastreabilidade>C:\ICC_GCC\ACTAS_DESMAT\IMAG\CSV_REJEITADO_RAST</caminhoRejeitadosRastreabilidade>
		<descompactarTemp>C:\ICC_GCC\ACTAS_DESMAT\IMAG\TEMPORARIO</descompactarTemp>
	</configuracao>
	
	<posicaoCsvGccd origem="2">
		<nomeDoArquivo>24</nomeDoArquivo>
		<agencia>20</agencia>
		<conta>21</conta>
		<tipoDaConta>22</tipoDaConta>
		<cpf>11</cpf>
	</posicaoCsvGccd>

	<!--“true”  - Habilita a extração do arquivo “.rast” de dentro da pasta “ZIP”.  Existindo o mesmo é enviado para a pasta de carga da rastreabilidade.
	“false” – Indica que não há arquivo .rast a ser extraído da pasta “ZIP”.-->
	<rastreabilidade gerar="true" moverRastreabilidade="false" trigger="true" validarIntegridade="true">
		
		<niur posicao="31" fixo=""/>
		<niurPrincipal posicao="32" fixo=""/>
		<hashImagem posicao="33" fixo=""/>
		<codigoFluxoArmazenamento posicao="34" fixo="1"/>
		<numeroProcesso posicao="35" fixo=""/>
		<bancoCaptura posicao="36" fixo=""/>
		<bancoProcessamento posicao="37" fixo=""/>
		<banco posicao="38" fixo=""/>
		<agenciaCaptura posicao="5" fixo=""/>
		<agenciaProcessamento posicao="40" fixo=""/>
		<agencia posicao="21" fixo=""/>
		<conta posicao="22" fixo=""/>
		<cpfCnpj posicao="6" fixo=""/>
		<filialCnpj posicao="10" fixo=""/>	
		<controleCpfCnpj posicao="15" fixo=""/>
		<!-- O icor pessoa auxilia na identificacao do tipo do documento se CPF/CNPJ, quando nao existir, a logica para determinar se o campo é cpf ou cnpj sera pela quantidade de caracteres (sendo o 3 os campos na mesma posicao do csv) -->
		<icorPessoa posicao="13" fixo=""/>
		<cmc7 posicao="39" fixo=""/>
		<situacaoIntegridade posicao="" fixo="2"/>
		<situacaoProcessamento posicao="" fixo="0"/>
		<situacaoDocumento posicao="40" fixo="1"/>
		<mimeType posicao="7" fixo=""/>
		<nomeArquivo posicao="25" fixo=""/>
		<codigoDocumento posicao="1" fixo=""/>
		<codigoServicoRecepcao>1</codigoServicoRecepcao>
		
	</rastreabilidade>
	
</tns:produto>
